# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # this seems to apply with
  # ls /sys/devices/platform/i8042/serio1/input/input*/
  # sudo udevadm test /sys/class/input/event16
  services.udev.extraHwdb = ''
    mouse:ps2::name:ETPS/2 Elantech TrackPoint:*
      POINTINGSTICK_SENSITIVITY=2

    input:b0011v0002p000Ee0000-e0,1,2,k110,111,112,r0,1,amlsfw
      POINTINGSTICK_SENSITIVITY=2

    input:b0000v0000p0000e0000-e0,5,kramlsfw2,
      POINTINGSTICK_SENSITIVITY=2

    evdev:name:ETPS/2 Elantech TrackPoint:dmi:bvn*:bvr*:bd*:svnLENOVO:pn*:pvr*:*
      POINTINGSTICK_SENSITIVITY=2
  '';

  # as soon as i upgrade 5.16
  # also: upstream it https://github.com/NixOS/nixos-hardware/pull/438
  #boot = lib.mkIf (lib.versionAtLeast config.boot.kernelPackages.kernel.version "5.17") {
  #  kernelParams = [ "initcall_blacklist=acpi_cpufreq_init" ];
  #  kernelModules = [ "amd-pstate" ];
  #};

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  # with linux 5.10 lts, BT audio works. With latest it doesnt.
  boot.kernelModules = [ "kvm-amd" ];
  # boot.kernelPackages = pkgs.linuxPackages; # _latest; 
  boot.kernelPackages = let
      linux_ioregionfd = pkgs.callPackage ./linux-ioregionfd.nix {};
    in
      pkgs.lib.mkDefault (pkgs.recurseIntoAttrs (pkgs.linuxPackagesFor linux_ioregionfd));
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zroot/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E25-330D";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "zroot/root/home";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { device = "zroot/root/tmp";
      fsType = "zfs";
    };

  swapDevices = [ ];

}
