# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    # device = "/dev/disk/by-uuid/69760ea0-7597-472f-b19f-cb47a73076c8";
    device = "/dev/disk/by-uuid/df5c7181-43ea-450f-b894-f0288d2449e3;
    fsType = "ext4";
  };

  fileSystems."/boot" = { 
    # device = "/dev/disk/by-uuid/6FDD-EA58";
    device = "/dev/disk/by-uuid/E95B-B644";
    fsType = "vfat";
  };

  fileSystems."/home/peter/.ssh" = {
    device = "/home/peter/.ssh";
    fsType = "9p";
    # skip mount in nested qemu;
  };
  # #o#p#t#i#o#n#s# #=# #[# #"#t#r#a#n#s#=#v#i#r#t#i#o#"# #"#n#o#f#a#i#l#"# #]#;#

  services.logind.extraConfig = ''
    RuntimeDirectorySize=70%
  '';
  swapDevices = [ ];

}
